spring.datasource.url=${DATABASE_URL:jdbc:h2:mem:testdb}
spring.datasource.username=${DATABASE_USERNAME:sa}
spring.datasource.password=${DATABASE_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
jwt.secret=f0b07bf68e039dff1bf944ecdd019224b21090a3bb72dfef444a431949e170ce
